import {open,lstat} from 'node:fs/promises';import{constants}from'node:fs';import{isAbsolute,basename}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{FalError,UsageError}from'./errors.js';import operations from'../tools/operations.json'with{type:'json'};
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown;explode?:boolean};const MAX=5*1048576;
const routes=operations.map(o=>({method:o.method,regex:new RegExp('^'+o.path.replace(/[.*+?^$()|[\]\\]/g,'\\$&').replace(/\{[^}]+\}/g,'([^/]+)')+'$')}));
export function modelParts(id:string){if(typeof id!=='string'||id.length>240||!/^([A-Za-z0-9_-][A-Za-z0-9_.-]*\/){1,7}[A-Za-z0-9_-][A-Za-z0-9_.-]*$/.test(id)||id.split('/').some(s=>s==='.'||s==='..'||s==='requests'))throw new UsageError('Invalid model_id; use the exact current catalog endpoint, without URLs, escapes or traversal.');const p=id.split('/');const n=['workflows','comfy'].includes(p[0]!)?3:2;if(p.length<n)throw new UsageError('Invalid namespaced model_id.');return{inference:id,root:p.slice(0,n).join('/')};}
export class FalClient{
 private tokens=new Map<string,string>();private schedule:Promise<void>=Promise.resolve();private nextAt=0;
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.map(a=>a.apiToken),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token|identity)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|api_key|signing_key|api_token|token|signed_url|upload_url|access_token|refresh_token|authorization|client_secret)$/i.test(k)?'[redacted]':this.sanitize(x)]));return v;}
 private async token(a:Account){if(this.tokens.has(a.name))return this.tokens.get(a.name)!;let token=a.apiToken;if(a.tokenFile){let file;try{if(!isAbsolute(a.tokenFile))throw Error();if(!(await lstat(a.tokenFile)).isFile())throw Error();file=await open(a.tokenFile,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new FalError('Cannot read the private Fal token file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new FalError('No valid API key configured for the selected account profile. Run fal-ai-cli login.',0,'CONFIG');this.tokens.set(a.name,token);return token;}
 private async pace(){const next=this.schedule.catch(()=>{}).then(async()=>{const delay=Math.max(0,this.nextAt-Date.now());if(delay)await this.sleep(delay);this.nextAt=Date.now()+this.config.minIntervalMs;});this.schedule=next;await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new FalError('Response exceeds the 5 MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 private async send(url:URL,method:string,body:unknown,hint:string|undefined,extra:Record<string,string>={},anonymous=false){const headers:Record<string,string>={Accept:'application/json'};if(!anonymous||this.config.accounts.length||hint!==undefined)headers.Authorization='Key '+await this.token(selectAccount(this.config,hint));for(const[k,v]of Object.entries(extra)){if(/[\r\n]/.test(v)||['authorization','host','cookie'].includes(k.toLowerCase()))throw new UsageError('Unsupported or invalid provider header.');headers[k]=v;}const encoded=body===undefined?undefined:JSON.stringify(body);if(encoded!==undefined){if(Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds 1 MiB JSON limit.');headers['Content-Type']='application/json';}await this.pace();let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new FalError('Fal request failed or timed out. Its outcome may be unknown; no automatic retry. Inspect provider request history before deliberately repeating.',0,'NETWORK');}const bytes=await this.bytes(response);if(!response.ok){let detail='';try{detail=JSON.stringify(this.sanitize(JSON.parse(bytes.toString('utf8')))).slice(0,1000);}catch{}throw new FalError('Fal API '+response.status+(response.status===429?' rate limit':'')+(detail?': '+detail:''),response.status,response.status===429?'RATE_LIMIT':[401,403].includes(response.status)?'AUTH':'API_ERROR');}if(response.status===204||!bytes.length)return{http_status:response.status,success:true};let parsed;try{parsed=JSON.parse(bytes.toString('utf8'));}catch{throw new FalError('Fal returned a non-JSON response; no automatic retry.');}if(parsed===null||typeof parsed!=='object')throw new FalError('Invalid Fal JSON response.');return parsed;}
 async request(method:string,path:string,query:QueryParam[]=[],body?:unknown,hint?:string,headers:Record<string,string>={}){if(!routes.some(r=>r.method===method&&r.regex.test(path))||/[?#\\]/.test(path)||/%2f|%5c|%00/i.test(path)||path.split('/').some(s=>['.','..'].includes(decodeURIComponent(s))))throw new UsageError('Unsupported Fal API method or path.');const url=new URL('/v1'+path,'https://api.fal.ai');for(const p of query){if(p.value===undefined||p.value===null)continue;if(Array.isArray(p.value)){if(p.explode===false)url.searchParams.set(p.name,p.value.join(','));else for(const v of p.value)url.searchParams.append(p.name,String(v));}else if(typeof p.value==='object')throw new UsageError('Object query parameters are unsupported.');else url.searchParams.set(p.name,String(p.value));}return this.send(url,method,body,hint,headers,method==='GET'&&path==='/models');}
 async generation(kind:'run'|'submit',id:string,input:Json,hint?:string,lifecycle?:Json,storeIO=false){const model=modelParts(id),url=new URL('/'+model.inference,kind==='run'?'https://fal.run':'https://queue.fal.run');const headers:Record<string,string>={'X-Fal-Store-IO':storeIO?'1':'0'};if(lifecycle)headers['X-Fal-Object-Lifecycle-Preference']=JSON.stringify(lifecycle);return this.send(url,'POST',input,hint,headers);}
 async job(kind:'status'|'result'|'cancel',id:string,requestId:string,hint?:string,logs=false){if(!/^[A-Za-z0-9_-]{1,128}$/.test(requestId))throw new UsageError('Invalid request_id; supply the exact returned identifier, without URLs or traversal.');const root=modelParts(id).root;const url=new URL('/'+root+'/requests/'+requestId+(kind==='status'?'/status':kind==='cancel'?'/cancel':''),'https://queue.fal.run');if(kind==='status')url.searchParams.set('logs',logs?'1':'0');return this.send(url,kind==='cancel'?'PUT':'GET',undefined,hint);}
 async upload(filePath:string,contentType:string,hint?:string,lifecycle?:Json){if(!isAbsolute(filePath)||!/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/i.test(contentType))throw new UsageError('Upload requires absolute file_path and a plain MIME content_type.');let f;let bytes:Buffer;try{if(!(await lstat(filePath)).isFile())throw Error();f=await open(filePath,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const st=await f.stat();if(!st.isFile()||st.size<1||st.size>20*1048576)throw Error();bytes=await f.readFile();if(bytes.length!==st.size||bytes.length>20*1048576)throw Error();}catch{throw new UsageError('Upload file must be a regular non-symlink file of 1 byte–20 MiB; no local bytes have been sent.');}finally{await f?.close();}const extra:Record<string,string>=lifecycle?{'X-Fal-Object-Lifecycle':JSON.stringify(lifecycle)}:{};const receipt=await this.send(new URL('https://rest.fal.ai/storage/upload/initiate?storage_type=fal-cdn-v3'),'POST',{file_name:basename(filePath),content_type:contentType},hint,extra);let upload:URL,file:URL;try{upload=new URL(receipt.upload_url);file=new URL(receipt.file_url);}catch{throw new FalError('Upload preparation returned invalid URLs. No bytes uploaded; no automatic retry.');}const safe=(u:URL)=>u.protocol==='https:'&&u.port===''&&!u.username&&!u.password&&(u.hostname==='fal.media'||u.hostname.endsWith('.fal.media'));
 if(!safe(upload)||!safe(file))throw new FalError('Upload preparation returned an unsupported CDN host. No local bytes uploaded. No automatic retry.');await this.pace();let r;try{r=await this.fetcher(upload,{method:'PUT',redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers:{'Content-Type':contentType},body:bytes! as any});}catch{throw new FalError('CDN upload failed or timed out; its outcome may be unknown. No automatic retry.');}if(!r.ok){await r.body?.cancel();throw new FalError('CDN upload HTTP '+r.status+'; no automatic retry.',r.status);}await r.body?.cancel();return{uploaded:true,file_url:receipt.file_url,bytes:bytes!.length,content_type:contentType,notice:'The selected local bytes were uploaded to fal. Account/lifecycle ACL and expiry apply; default CDN access can be public. No automatic model run or local deletion.'};}
}
