import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{FalClient,modelParts,type Json,type QueryParam}from'../api/client.js';import{FalError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:FalClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,allowUnionTypes:true});(addFormats as unknown as(a:Ajv)=>void)(ajv);
// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const bodyValidators=new Map<string,ValidateFunction>();function bodyValidator(op:Operation):ValidateFunction{let v=bodyValidators.get(op.name);if(!v){v=ajv.compile(op.bodySchema!);bodyValidators.set(op.name,v);}return v;}

function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.bodySchema?.properties??{});properties.account={type:'string',description:'Exact private account key profile label, not an authenticated provider owner ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation, paid work or private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON body, mutually exclusive with flat body flags and payload_file. Use schema for union bodies.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink private JSON file, at most 1 MiB. Cannot mix with other body inputs.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new owner-private file; signed credential URL is never echoed.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||!(await lstat(path)).isFile())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const st=await f.stat();if(!st.isFile()||st.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON file, at most 1 MiB.');}finally{await f?.close();}}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');const body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('Provide the required native body; inspect schema first.');if(op.bodySchema)check(bodyValidator(op),body);if(op.method==='PATCH'&&body&&typeof body==='object'&&!Object.keys(body).length)throw new UsageError('Provide at least one update field.');if(args.exclude_api_requests&&args.only_api_requests)throw new UsageError('exclude_api_requests and only_api_requests cannot both be true.');if(op.name==='search_models'&&args.limit!==undefined&&args.limit>100)throw new UsageError('Local model page limit is 100.');const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));const headers=Object.fromEntries(op.params.filter(p=>p.in==='header'&&args[p.key]!==undefined).map(p=>[p.name,String(args[p.key])]));return{method:op.method,path,query,body,headers};}
async function execute(op:Operation,args:Json,client:FalClient){const call=await prepare(op,args);if(!op.privateOutput)return client.sanitize(await client.request(call.method,call.path,call.query,call.body,args.account,call.headers));if(!isAbsolute(args.output_file))throw new UsageError('output_file must be absolute.');let f;try{f=await open(args.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file; select a new file in an existing private directory.');}try{const data=await client.request(call.method,call.path,call.query,call.body,args.account,call.headers);if(typeof data.signed_url!=='string'||!data.signed_url)throw new FalError('Signed URL response is incomplete; no automatic retry.');const bytes=Buffer.from(JSON.stringify(data)+'\n');await f.writeFile(bytes);return{saved:true,output_file:args.output_file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),notice:'Signed URL is an access credential; saved only to the requested exclusive private file. Keep parent directory and Windows ACL private.'};}catch(e){await f.close();f=undefined;await unlink(args.output_file).catch(()=>{});throw e;}finally{await f?.close();}}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact configured isolated API-key profile label.'},confirm={type:'boolean',description:'Explicit approval for the requested paid work, mutation, upload or private file.'},model_id={type:'string',minLength:3,maxLength:240,description:'Exact current catalog endpoint ID. Never guess model names or parameter mappings.'},request_id={type:'string',pattern:'^[A-Za-z0-9_-]{1,128}$',description:'Exact queue receipt ID; status/result/cancel use its owner/app root, without inference subpaths.'};
const acl={type:'object',properties:{default:{type:'string',enum:['allow','forbid','hide']},rules:{type:'array',maxItems:100,items:{type:'object',properties:{user:{type:'string',minLength:1},decision:{type:'string',enum:['allow','forbid','hide']}},required:['user','decision'],additionalProperties:false}}},required:['default'],additionalProperties:false};
const lifecycle={type:'object',properties:{expiration_duration_seconds:{type:['integer','null'],minimum:1},initial_acl:acl},additionalProperties:false,description:'Native CDN expiry/ACL preference. Omit to use account defaults. null expiration means no expiry; default CDN access may be public. Unknown nicknames may be dropped by provider.'};
const input={type:'object',description:'Exact native model inputs. Fetched current model JSON schema validates these before a paid request; no guessed prompt/image/duration adapters.'},store_io={type:'boolean',default:false,description:'Local default false sends X-Fal-Store-IO:0. true allows provider JSON payload storage; CDN media retention/ACL is separate.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'creative_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
function normalizeSchema(v:any):any{if(Array.isArray(v))return v.map(normalizeSchema);if(!v||typeof v!=='object')return v;const o=Object.fromEntries(Object.entries(v).filter(([k])=>!['example','examples','nullable','discriminator','xml','readOnly','writeOnly','$schema','$id'].includes(k)).map(([k,x])=>[k,normalizeSchema(x)]))as Json;for(const[key,base]of[['exclusiveMinimum','minimum'],['exclusiveMaximum','maximum']])if(typeof o[key!]==='boolean'){if(o[key!]&&typeof o[base!]==='number'){o[key!]=o[base!];delete o[base!];}else delete o[key!];}if(v.nullable){if(o.type)o.type=typeof o.type==='string'?[o.type,'null']:[...o.type,'null'];else return{anyOf:[o,{type:'null'}]};if(o.enum&&!o.enum.includes(null))o.enum.push(null);}return o;}
async function modelInfo(id:string,c:FalClient,hint?:string){modelParts(id);const data=await c.request('GET','/models',[{name:'endpoint_id',value:id},{name:'expand',value:'openapi-3.0'}],undefined,hint);const model=data.models?.find((m:Json)=>m.endpoint_id===id);if(!model)throw new FalError('Model not found in current exact catalog lookup.',404,'NOT_FOUND');return model;}
function inputValidator(model:Json){const doc=model.openapi;if(!doc||typeof doc!=='object')throw new UsageError('Current model input schema is unavailable; no paid request submitted.');const postPaths=Object.entries(doc.paths??{}).filter(([,v])=>(v as Json).post);let body=doc.paths?.['/'+model.endpoint_id]?.post?.requestBody?.content?.['application/json']?.schema;if(!body&&postPaths.length===1)body=(postPaths[0]![1]as Json).post.requestBody?.content?.['application/json']?.schema;if(!body){const candidates=Object.entries(doc.components?.schemas??{}).filter(([k])=>['input','request'].includes(k.toLowerCase()));if(candidates.length===1)body={$ref:'#/components/schemas/'+candidates[0]![0]};}if(!body)throw new UsageError('Current model input schema is missing or ambiguous; no paid request submitted.');if(JSON.stringify(doc).match(/"\$ref"\s*:\s*"(?!#\/)/))throw new UsageError('External model schema references are unsupported; no remote schema URLs fetched.');const schema={...normalizeSchema(body),components:normalizeSchema(doc.components??{})};let v;try{v=ajv.compile(schema);}catch{throw new UsageError('Current model input schema cannot be safely compiled; no paid request submitted.');}return{schema,validate:v};}
async function validatedGeneration(a:Json,c:FalClient){const selected=selectAccount(c.config,a.account);const model=await modelInfo(a.model_id,c,selected.name),spec=inputValidator(model);check(spec.validate,a.input);return{modelId:a.model_id,input:a.input,lifecycle:a.lifecycle??null,storeIO:a.store_io===true,inputSchemaSha256:hash(spec.schema)};}
helper('get_model_info','Inspect current model metadata/schema','Exact current catalog lookup with OpenAPI expansion. No generation or inferred model defaults. Schema may be unavailable; inspect actual native fields.','read',{model_id,account},['model_id'],async(a,c)=>modelInfo(a.model_id,c,a.account));
for(const[name,kind,title]of[['run_model','run','Run one model synchronously'],['submit_job','submit','Submit one queued job'],['generate_image','submit','Submit image generation'],['generate_video','submit','Submit video generation']]as const)helper(name,title,'Confirmed paid model request after current native input-schema validation. Exact model_id/input required; image/video commands do not invent fields or choose a default. Queue submissions return receipt only; synchronous timeout may leave an unknown paid outcome. No retry or polling.','destructive',{model_id,input,lifecycle,store_io,account,confirm},['model_id','input'],async(a,c)=>{await validatedGeneration(a,c);const result=await c.generation(kind,a.model_id,a.input,a.account,a.lifecycle,a.store_io===true);if(kind==='submit'&&typeof result.request_id!=='string')throw new FalError('Queue submission response lacks request_id; paid outcome may be unknown. Inspect provider history before repeating.');return{model_id:a.model_id,...(kind==='submit'?{submitted:true,completed:false}:{}),result:c.sanitize(result)};});
helper('get_job_status','Read queue status once','One read using the SDK-compatible owner/app root, not the full model subpath. No auto-polling, paid re-submission or arbitrary status URL.','read',{model_id,request_id,logs:{type:'boolean',default:false,description:'Include native provider logs only when requested.'},account},['model_id','request_id'],(a,c)=>c.job('status',a.model_id,a.request_id,a.account,a.logs===true));
helper('get_job_result','Read completed queue result once','One result read using the receipt/model root. No wait loop, media download, re-submission or auto-upload. Signed credential URLs are redacted; ordinary output media URLs remain account data.','read',{model_id,request_id,account},['model_id','request_id'],(a,c)=>c.job('result',a.model_id,a.request_id,a.account));
helper('cancel_job','Request queue cancellation','Confirmed native cancellation request. Cancellation receipt is not proof processing stopped or credits were refunded; current provider state controls eligibility. No retry.','destructive',{model_id,request_id,account,confirm},['model_id','request_id'],(a,c)=>c.job('cancel',a.model_id,a.request_id,a.account));
helper('upload_file','Upload one local input file','Confirmed selected absolute regular non-symlink local file, 1 byte–20 MiB. Uses pinned SDK upload-initiation protocol then a credential-free HTTPS fal.media PUT with redirects refused. No remote URL ingestion, base64 model output, multipart retries or automatic generation.','destructive',{file_path:{type:'string',minLength:1,description:'Absolute selected local media file, regular/non-symlink, 1 byte–20 MiB.'},content_type:{type:'string',pattern:'^[a-zA-Z0-9.+-]+/[a-zA-Z0-9.+-]+$',description:'Plain MIME type matching the selected media.'},lifecycle,account,confirm},['file_path','content_type'],(a,c)=>c.upload(a.file_path,a.content_type,a.account,a.lifecycle));
helper('list_accounts','List configured private accounts','Local labels/default/auth method only. No keys, token paths, real provider identities or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,auth:a.tokenFile?'token_file':a.apiToken?'api_key':'not_configured'}))}));
helper('get_operation_schema','Inspect native platform operation','Local current native method/path/query/header/body schema and exact provenance. No credential or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name)}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const tasks={type:'array',minItems:1,maxItems:10,description:'One to ten ordered async generation payloads. CLI repeats --tasks individual JSON objects. One job can produce several outputs; this is not a cost or output-count budget.',items:{type:'object',properties:{model_id,input,lifecycle,store_io},required:['model_id','input'],additionalProperties:false}};
async function review(a:Json,c:FalClient){const selected=selectAccount(c.config,a.account),validated=[];for(const task of a.tasks)validated.push(await validatedGeneration({...task,account:selected.name},c));const ids=[...new Set<string>(a.tasks.map((t:Json)=>t.model_id))];const prices=await c.request('GET','/models/pricing',[{name:'endpoint_id',value:ids,explode:true}],undefined,selected.name);const quotes=ids.map(id=>{const p=prices.prices?.find((p:Json)=>p.endpoint_id===id);if(!p||typeof p.unit_price!=='number'||typeof p.unit!=='string'||typeof p.currency!=='string')throw new UsageError('Current unit pricing unavailable for a reviewed model; no paid request submitted.');return{endpoint_id:id,unit_price:p.unit_price,unit:p.unit,currency:p.currency};});return{version:1,profile:selected.name,snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:validated,unitPricing:quotes};}
helper('preview_generation_batch','Review ordered generation batch','Read-only current schema validation and native unit-pricing lookup for all requested async jobs. Hash binds ordered exact inputs/lifecycle/store-IO/profile label/current schemas/unit quotes. Unit pricing is not final cost or a spending cap. No generation, file write or key ownership validation.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await review(a,c);return{review:c.sanitize(r),reviewSha256:hash(r),paidRequests:0,notice:'Not a final cost guarantee, budget, real owner check, provider-state lock or human approval. Inspect exact native inputs, output counts and model pricing before explicitly approving.'};});
helper('submit_generation_batch','Submit exact reviewed generation batch','Confirmed one-to-ten async jobs. Refetch all current schemas/unit quotes and validate all before first paid submission; refuse changed hash. Submit sequentially, stop on first failure, report known request IDs/failed and unattempted indices. No polling, retries, rollback, continuation or budget guarantee.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$'}},['tasks','review_sha256'],async(a,c)=>{const r=await review(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; current inputs/order/profile/schema/unit pricing changed. Preview again; no paid request submitted.');const completed:Json[]=[];for(let i=0;i<r.tasks.length;i++){const t=r.tasks[i]!;try{const result=await c.generation('submit',t.modelId,t.input,r.profile,t.lifecycle??undefined,t.storeIO);if(typeof result.request_id!=='string')throw new FalError('Queue response lacks request_id; outcome may be unknown.');completed.push({index:i,model_id:t.modelId,request_id:result.request_id,receipt:c.sanitize(result)});}catch(e){const err=e as FalError;throw new FalError(JSON.stringify(c.sanitize({notice:'Batch stopped. Earlier jobs may still run and spend credits; failed submission may have an unknown outcome. Check provider history before repeating. No retry, rollback or automatic cancellation.',completed,failedIndex:i,unattemptedIndices:r.tasks.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{submitted:true,completed:false,receipts:completed};});
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}export function validateArguments(tool:ToolSpec,args:Json){check(validatorFor(tool),args);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);for(const o of operations)if(o.bodySchema)bodyValidator(o);return validators.size+bodyValidators.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
